language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq jlex cup openjdk-6-jdk
  - sudo apt-get install -qq g++ 
  - cd source
env: CLASSPATH=".:/usr/share/java/JLex.jar:/usr/share/java/cup.jar"
